[workspace]

[package]
name = "rust-third-party"
version = "0.0.0"
publish = false
edition = "2021"

# Dummy target to keep Cargo happy
[[bin]]
name = "fake"
path = "top/main.rs"

[dependencies]
rustversion = "1.0"
inventory = "0.3"
linkme = { git = "https://github.com/dtolnay/linkme.git" }

[patch.crates-io]
