omit_targets = []
extra_srcs = []
omit_srcs = []
rustc_flags = []
cfgs = []
features = []
omit_features = []
extra_deps = []
omit_deps = []
# use auto cfg inside the build.rs
cargo_env = true

[env]

[[buildscript]]
# output rustc flags to enable simd in aarch64
[buildscript.rustc_flags]

[extra_mapped_srcs]

[platform_fixup]
