[workspace]
members = ["bubble", "bubble_alloc", "bubble_core", "bubble_macros", "bubble_tasks", "dyntls"]
resolver = "2"

[workspace.dependencies]
bubble-core = { path = "bubble_core", version = "0.1.0" }
bubble-tasks = { path = "bubble_tasks", version = "0.1.0" }